version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/FairShare.Api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/src/FairShare.Web"
    schedule:
      interval: "weekly"
