services:
  fairshare:
    image: ghcr.io/jjwren/fairshare:latest
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_HTTP_PORTS: "9090"   # container listens on 9090
      UI__DefaultTheme: "dark"        # light|dark|auto
      AdminSeed__Enabled: "true"      # this pulls the initial admin config from the docker-compose/env that you will create for this
      AdminSeed__User: "${AdminSeed__User}"    # this should be set in an .env file
      AdminSeed__Password: "${AdminSeed__Password}"    # this should be set in an .env file
      AdminSeed__LogGeneratedPassword: "true"
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9090/healthz"]
      interval: 10s
      timeout: 2s
      retries: 6
    restart: unless-stopped
