// <auto-generated />
using System;
using FairShare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FairShare.Migrations
{
    [DbContext(typeof(FairShareDbContext))]
    partial class FairShareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FairShare.Models.ParentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPrimaryCustody")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthcareCoverageCosts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyGrossIncome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreexistingAlimony")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreexistingChildSupport")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkRelatedChildcareCosts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("MonthlyGrossIncome", "PreexistingChildSupport", "PreexistingAlimony", "WorkRelatedChildcareCosts", "HealthcareCoverageCosts", "HasPrimaryCustody")
                        .HasDatabaseName("IX_ParentProfile_DuplicateSig");

                    b.ToTable("ParentProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
