#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=4

banner "FairShare — Sign in with Google setup"

# ── Stage 1: which deployment gets Google sign-in ─────────────────────────
stage "Deployment target"
say "This wizard creates a Google OAuth client and wires it into a FairShare stack."
say "Values land in that stack's .env; the stack is restarted at the end."
printf '  %sPath to the stack .env%s %s[Enter = /z/docker/fairshare/.env]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
read -r FAIRSHARE_ENV_PATH || true
FAIRSHARE_ENV_PATH="${FAIRSHARE_ENV_PATH:-/z/docker/fairshare/.env}"
ENV_FILE="$FAIRSHARE_ENV_PATH"
[[ -f "$ENV_FILE" ]] || warn "no file at $ENV_FILE yet — it will be created"
printf '  %sPublic API origin%s %s[Enter = https://api.easychildsupport.fyi]%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
read -r FAIRSHARE_API_ORIGIN || true
FAIRSHARE_API_ORIGIN="${FAIRSHARE_API_ORIGIN:-https://api.easychildsupport.fyi}"
REDIRECT_URI="${FAIRSHARE_API_ORIGIN%/}/signin-google"
say ""
say "The authorized redirect URI for this deployment is:"
say "  ${BOLD}${REDIRECT_URI}${RESET}"
note "(Google sends the sign-in result there; the API turns it into a FairShare session.)"
pause

# ── Stage 2: Google Cloud project + consent screen ────────────────────────
stage "Google Cloud — project and consent screen"
say "Google sign-in needs a (free) Google Cloud project with a consent screen."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project named 'FairShare' (or select an existing one in the top bar)."
step "Then go to: APIs & Services → OAuth consent screen (a.k.a. 'Google Auth Platform')."
step "Choose user type 'External', app name 'FairShare', and your email as support/developer contact."
step "Authorized domain: the site's domain (e.g. easychildsupport.fyi). Add no extra scopes."
step "Finish the screens, then PUBLISH the app (move it out of 'Testing')."
note "In Testing mode only allow-listed Google accounts could sign in — publishing lifts that."
step "Branding links: set the app home page to your site's URL, privacy policy to"
step "  {site}/privacy and terms of service to {site}/terms (both ship with FairShare)."
note "Requesting Google's app VERIFICATION later? The site's domain must be verified in"
note "Google Search Console with THIS SAME account first, and the home page must show the"
note "app name and purpose (FairShare's landing page does). See docs/SETUP.md section 4."
warn "Google may show a 'needs verification' note for the logo/branding — plain email scope"
warn "sign-in keeps working without verification."
pause "Done with the consent screen? Press Enter."

# ── Stage 3: create the OAuth client and capture its keys ─────────────────
stage "Google Cloud — OAuth client"
open_url "https://console.cloud.google.com/apis/credentials"
step "Click: Create credentials → OAuth client ID."
step "Application type: Web application. Name: FairShare."
step "Under 'Authorized redirect URIs' add EXACTLY:"
say "    ${BOLD}${REDIRECT_URI}${RESET}"
note "No 'Authorized JavaScript origins' are needed — the flow is server-driven."
step "Click Create. A dialog shows the Client ID and Client secret."
ask GOOGLE_CLIENT_ID "Paste the Client ID (ends googleusercontent.com):"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret (hidden):"

# ── Stage 4: save and restart the stack ───────────────────────────────────
stage "Save and restart"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
STACK_DIR="$(dirname "$ENV_FILE")"
say "The API only reads these at startup, so the stack needs a restart."
if confirm "Run 'docker compose up -d' in $STACK_DIR now?"; then
  ( cd "$STACK_DIR" && docker compose up -d )
  say "Waiting for the API to come back..."
  sleep 8
  if command -v curl >/dev/null 2>&1 && curl -fsS "${FAIRSHARE_API_ORIGIN%/}/api/v1/auth/config" 2>/dev/null | grep -qi '"googleEnabled": *true'; then
    say "${GREEN}✓ The API reports googleEnabled: true — the Google button is live.${RESET}"
  else
    warn "Could not confirm via ${FAIRSHARE_API_ORIGIN%/}/api/v1/auth/config — check it in a browser."
    note "(On the host, hairpin NAT can block the public URL; the login page is the real test.)"
  fi
else
  SKIPPED+=("restart the stack: cd $STACK_DIR && docker compose up -d")
fi

finish
