name: Release (create PR, tag, changelog)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please (manifest)
        uses: googleapis/release-please-action@v4
